variables:
  - ${{ if eq(parameters.environment, 'dev') }}:
      - group: wso2-apim-IaC-${{ parameters.environment }}

  - ${{ if eq(parameters.environment, 'qa') }}:
      - group: wso2-apim-IaC-${{ parameters.environment }}

  - ${{ if eq(parameters.environment, 'pdn') }}:
      - group: wso2-apim-IaC-${{ parameters.environment }}


  - name: TF_WORKING_DIR
    value: ${{ format('envs/{0}', parameters.environment) }}
